name: devlopment-image-build

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    name: publish development image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          #platforms: linux/arm64/v8,linux/amd64,linux/arm/v7
          platforms: linux/amd64
          push: true
          tags: meetahladar/portfolio:latest

  deploy:
    needs: publish
    name: deploy development image
    runs-on: ubuntu-latest

    steps:  
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 65504   
          script: |
            docker stop portfolio || true
            docker rm portfolio || true 
            docker pull meetahladar/portfolio:latest
            docker run -d --name portfolio --restart unless-stopped -p 3000:3000 -v /root/docker/portfolio/.env:/usr/src/.env meetahladar/portfolio:latest
            